### ISSUE TITLE
Views of type form not available in Koo

### ISSUE THREAD

**Issue by amatmv** [gisce/openerp-client-kde#99]
![image](https://user-images.githubusercontent.com/11032995/43512794-58e58d92-957c-11e8-9dcc-3bcfedd52b49.png)

**Comment by Xevib** [comment]
@amatmv Thx for the report, can you test it on this PR https://github.com/gisce/openerp-client-kde/pull/84
I think this fixes the load of the fields types

**Comment by amatmv** [comment]
@Xevib i'm on [fix_plugin_scan](https://github.com/gisce/openerp-client-kde/tree/fix_plugin_scan) branch and the tree view works neither the form view. 
It doesn't even open a list.  :confused:

**Comment by Xevib** [comment]
@amatmv as we seen the problem was with the the system packages so I added a updated readme with the ubuntu requirements https://github.com/gisce/openerp-client-kde/pull/102
